name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - run:
          command: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts
      - run: |
          sudo -u root createuser -h localhost --superuser ubuntu &&
          sudo createdb -h localhost test_db
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name:
            a1_msgs
            a1_driver
          target-ros2-distro: foxy
          vcs-repo-file-url: unitree_a1_ros2.repos
